apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parrot
  template:
    metadata:
      labels:
        app: parrot
    spec:
      containers:
        - name: parrot-c
          image: mravily/parrot:v1
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
